In [1]:
import torch 
import math


In [2]:
x = torch.empty(3, 4) 
print(type(x)) 
print(x)

<class 'torch.Tensor'>
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [3]:
zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)


tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [4]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)


tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


In [5]:
x = torch.empty(2, 2, 3)
print(x.shape)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)


torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])


In [6]:
some_constants = torch.tensor([[3.1415926, 2.71828], [1.61803, 0.0072897]])
print(some_constants)

some_integers = torch.tensor((2, 3, 5, 7, 11, 13, 17, 19))
print(some_integers)

more_integers = torch.tensor(((2, 4, 6), [3, 6, 9]))
print(more_integers)


tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]])
tensor([ 2,  3,  5,  7, 11, 13, 17, 19])
tensor([[2, 4, 6],
        [3, 6, 9]])


In [7]:
a = torch.ones((2, 3), dtype=torch.int16)
print(a)

b = torch.rand((2, 3), dtype=torch.float64) * 20.
print(b)

c = b.to(torch.int32)
print(c)


tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[ 0.9956,  1.4148,  5.8364],
        [11.2406, 11.2083, 11.6692]], dtype=torch.float64)
tensor([[ 0,  1,  5],
        [11, 11, 11]], dtype=torch.int32)


In [8]:
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)


tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [9]:
powers2 = twos ** torch.tensor([[1, 2], [3, 4]])
print(powers2)

fives = ones + fours
print(fives)

dozens = threes * fours
print(dozens)


tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


In [10]:
a = torch.ones(4, 3, 2)

# 3rd & 2nd dims identical to a, dim 1 absent
b = a * torch.rand(3, 2) 
print(b)

# 3rd dim = 1, 2nd dim identical to a
c = a * torch.rand(3, 1) 
print(c)

# 3rd dim identical to a, 2nd dim = 1
d = a * torch.rand(1, 2) 
print(d)


tensor([[[0.6146, 0.5999],
         [0.5013, 0.9397],
         [0.8656, 0.5207]],

        [[0.6146, 0.5999],
         [0.5013, 0.9397],
         [0.8656, 0.5207]],

        [[0.6146, 0.5999],
         [0.5013, 0.9397],
         [0.8656, 0.5207]],

        [[0.6146, 0.5999],
         [0.5013, 0.9397],
         [0.8656, 0.5207]]])
tensor([[[0.6865, 0.6865],
         [0.3614, 0.3614],
         [0.6493, 0.6493]],

        [[0.6865, 0.6865],
         [0.3614, 0.3614],
         [0.6493, 0.6493]],

        [[0.6865, 0.6865],
         [0.3614, 0.3614],
         [0.6493, 0.6493]],

        [[0.6865, 0.6865],
         [0.3614, 0.3614],
         [0.6493, 0.6493]]])
tensor([[[0.2633, 0.4762],
         [0.2633, 0.4762],
         [0.2633, 0.4762]],

        [[0.2633, 0.4762],
         [0.2633, 0.4762],
         [0.2633, 0.4762]],

        [[0.2633, 0.4762],
         [0.2633, 0.4762],
         [0.2633, 0.4762]],

        [[0.2633, 0.4762],
         [0.2633, 0.4762],
         [0.2633, 0.4762]]])


In [11]:
a = torch.ones(4, 3, 2)

b = a * torch.rand(4, 3)    # dimensions must match last-to-first


RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2

In [12]:
a = torch.ones(4, 3, 2)

c = a * torch.rand(   2, 3) # both 3rd & 2nd dims different

d = a * torch.rand((0, ))   # can't broadcast with an empty tensor

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2

In [13]:
a = torch.ones(4, 3, 2)

d = a * torch.rand((0, ))   # can't broadcast with an empty tensor

RuntimeError: The size of tensor a (2) must match the size of tensor b (0) at non-singleton dimension 2

In [14]:
a = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('a:')
print(a)
print(torch.sin(a))   # this operation creates a new tensor in memory
print(a)              # a has not changed

b = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('\nb:')
print(b)
print(torch.sin_(b))  # note the underscore
print(b)              # b has changed


a:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 2.3562])

b:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7071, 1.0000, 0.7071])


In [15]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)
c = torch.zeros(2, 2)
old_id = id(c)

print(c)
d = torch.matmul(a, b, out=c)
print(c)                # contents of c have changed

assert c is d           # test c & d are same object, not just containing equal values
assert id(c) == old_id  # make sure that our new c is the same object as the old one

torch.rand(2, 2, out=c) # works for creation too!
print(c)                # the value in c has changed again
assert id(c) == old_id  # still the same object!


tensor([[0., 0.],
        [0., 0.]])
tensor([[0.2850, 0.6030],
        [0.3820, 0.3138]])
tensor([[0.0023, 0.4945],
        [0.3857, 0.9883]])


In [16]:
a = torch.ones(2, 2)
b = a.clone()

assert b is not a      # different objects in memory...
print(torch.eq(a, b))  # ...but still with the same contents!

a[0][1] = 561          # a changes...
print(b)               # ...but b is still all ones


tensor([[True, True],
        [True, True]])
tensor([[1., 1.],
        [1., 1.]])


In [17]:
if torch.cuda.is_available():
    my_device = torch.device('cuda')
    x = torch.rand(2, 2,   device='cuda')
    print(x)
else:
    my_device = torch.device('cpu')
print('Device: {}'.format(my_device))

y = torch.rand(2, 2, device=my_device)
print(y)


Device: cpu
tensor([[0.4762, 0.7242],
        [0.0776, 0.4004]])


In [18]:
a = torch.rand(2,3)
b = torch.rand(3,4)
c = torch.einsum("ik,kj->ij", a, b)
print(a)
print(b)
print(c)

tensor([[0.9877, 0.0352, 0.0905],
        [0.4485, 0.8740, 0.2526]])
tensor([[0.6923, 0.7545, 0.7746, 0.2330],
        [0.8441, 0.9004, 0.3995, 0.6324],
        [0.9464, 0.0113, 0.5183, 0.9807]])
tensor([[0.7992, 0.7780, 0.8260, 0.3412],
        [1.2873, 1.1282, 0.8275, 0.9049]])


In [19]:
a_scaler = torch.ones(1)
a_vec = torch.ones(3)
B = torch.arange(9).reshape(3,3).float()

print(a_scaler)
print(a_vec)
print(B)

out = torch.einsum("i,ij",a_scaler,B)
print(out)

out= torch.einsum("i,ij",a_vec,B)
print(out)

out = torch.einsum("j,ij",a_scaler,B)
print(out)

out = torch.einsum("j,ij",a_vec,B)
print(out)



tensor([1.])
tensor([1., 1., 1.])
tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
tensor([ 9., 12., 15.])
tensor([ 9., 12., 15.])
tensor([ 3., 12., 21.])
tensor([ 3., 12., 21.])


In [20]:
A = torch.eye(3)
B = torch.arange(9).reshape(3,3).float()

print(A)

print(B)

out = torch.einsum("ij,jk",A,B)
print(out)

out = torch.einsum("kj,ji",A,B)
print(out)


tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
tensor([[0., 3., 6.],
        [1., 4., 7.],
        [2., 5., 8.]])


In [21]:
A = torch.eye(3)
B = torch.arange(9).reshape(3,3).float()

print(A)

print(B)

out = torch.einsum("kj,ji",A,B)
print(out)

out = torch.einsum("kj,ji->ki",A,B)
print(out)


tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
tensor([[0., 3., 6.],
        [1., 4., 7.],
        [2., 5., 8.]])
tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])


In [22]:
A = torch.randn(2, 3, 4, 5)
torch.einsum('...ij->...ji', A).shape


torch.Size([2, 3, 5, 4])

In [ ]:
B = torch.arange(9).reshape(3,3).float()

print(B)

out = torch.einsum("ii->i",B)
print(out)

out = torch.einsum("ii",B)
print(out)

In [23]:
B = torch.arange(9).reshape(3,3).float()

print(B)

out = torch.einsum("ij->ji",B)
print(out)

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
tensor([[0., 3., 6.],
        [1., 4., 7.],
        [2., 5., 8.]])


In [24]:
B = torch.arange(9).reshape(3,3).float()

print(B)

out = torch.einsum("ij->",B)
print(out)

out = torch.einsum("ij->i",B)
print(out)

out = torch.einsum("ij->j",B)
print(out)

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
tensor(36.)
tensor([ 3., 12., 21.])
tensor([ 9., 12., 15.])


In [25]:
A = torch.eye(3)
B = torch.arange(9).reshape(3,3).float()

print(A)

print(B)

out = torch.einsum("ij,ij->ij",A,B)
print(out)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
tensor([[0., 0., 0.],
        [0., 4., 0.],
        [0., 0., 8.]])


In [26]:
a = torch.arange(1,5).float()
b = torch.arange(4).float()

print(a)

print(b)

out = torch.einsum("i,i ->",a,b)
print(out)

tensor([1., 2., 3., 4.])
tensor([0., 1., 2., 3.])
tensor(20.)


In [27]:
a = torch.arange(1,5).float()
b = torch.arange(4).float()

print(a)

print(b)

out = torch.einsum("i,j -> ij",a,b)
print(out)

tensor([1., 2., 3., 4.])
tensor([0., 1., 2., 3.])
tensor([[ 0.,  1.,  2.,  3.],
        [ 0.,  2.,  4.,  6.],
        [ 0.,  3.,  6.,  9.],
        [ 0.,  4.,  8., 12.]])


In [28]:
A = torch.eye(3)
B = torch.arange(9).reshape(3,3).float()

print(A)

print(B)

out = torch.einsum("ij,jk->ik",A,B)
print(out)


tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])


In [29]:
A = torch.ones(2,3,2)
B = torch.arange(12).reshape(2,2,3).float()

print(A)

print(B)

out = torch.einsum('ijk,ikl->ijl',A,B)
print(out)

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])
tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
tensor([[[ 3.,  5.,  7.],
         [ 3.,  5.,  7.],
         [ 3.,  5.,  7.]],

        [[15., 17., 19.],
         [15., 17., 19.],
         [15., 17., 19.]]])
